# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.resize(1060, 925)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/g00494853/.designer/backup/g.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QMainWindow.setWindowIcon(icon)
        QMainWindow.setAutoFillBackground(False)
        QMainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.QMessageBox = QtWidgets.QPushButton(self.centralwidget)
        self.QMessageBox.setGeometry(QtCore.QRect(20, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.QMessageBox.setFont(font)
        self.QMessageBox.setObjectName("QMessageBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(21, 21, 291, 148))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setKerning(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 0, 1, 1)
        self.Normal = QtWidgets.QLineEdit(self.layoutWidget)
        self.Normal.setInputMask("")
        self.Normal.setText("")
        self.Normal.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Normal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Normal.setObjectName("Normal")
        self.gridLayout.addWidget(self.Normal, 0, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_6.sizePolicy().hasHeightForWidth())
        self.lineEdit_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setKerning(True)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 0, 1, 1)
        self.NoEcho = QtWidgets.QLineEdit(self.layoutWidget)
        self.NoEcho.setText("")
        self.NoEcho.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.NoEcho.setObjectName("NoEcho")
        self.gridLayout.addWidget(self.NoEcho, 1, 1, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_7.sizePolicy().hasHeightForWidth())
        self.lineEdit_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setKerning(True)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 2, 0, 1, 1)
        self.Password = QtWidgets.QLineEdit(self.layoutWidget)
        self.Password.setText("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.gridLayout.addWidget(self.Password, 2, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setKerning(True)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 0, 1, 1)
        self.PasswordEchoOnEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.PasswordEchoOnEdit.setFont(font)
        self.PasswordEchoOnEdit.setText("")
        self.PasswordEchoOnEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.PasswordEchoOnEdit.setPlaceholderText("")
        self.PasswordEchoOnEdit.setObjectName("PasswordEchoOnEdit")
        self.gridLayout.addWidget(self.PasswordEchoOnEdit, 3, 1, 1, 1)
        self.PasswordEchoOnEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PasswordEchoOnEdit_3.setFont(font)
        self.PasswordEchoOnEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PasswordEchoOnEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.PasswordEchoOnEdit_3.setDragEnabled(False)
        self.PasswordEchoOnEdit_3.setReadOnly(True)
        self.PasswordEchoOnEdit_3.setObjectName("PasswordEchoOnEdit_3")
        self.gridLayout.addWidget(self.PasswordEchoOnEdit_3, 4, 0, 1, 1)
        self.PasswordEchoOnEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.PasswordEchoOnEdit_2.setFont(font)
        self.PasswordEchoOnEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.PasswordEchoOnEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.PasswordEchoOnEdit_2.setReadOnly(True)
        self.PasswordEchoOnEdit_2.setObjectName("PasswordEchoOnEdit_2")
        self.gridLayout.addWidget(self.PasswordEchoOnEdit_2, 4, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 180, 186, 18))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Yes = QtWidgets.QRadioButton(self.layoutWidget1)
        self.Yes.setObjectName("Yes")
        self.gridLayout_2.addWidget(self.Yes, 0, 0, 1, 1)
        self.No = QtWidgets.QRadioButton(self.layoutWidget1)
        self.No.setObjectName("No")
        self.gridLayout_2.addWidget(self.No, 0, 1, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 320, 291, 22))
        self.horizontalSlider.setMaximum(999)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(50)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.showdialog = QtWidgets.QPushButton(self.centralwidget)
        self.showdialog.setGeometry(QtCore.QRect(20, 360, 75, 23))
        self.showdialog.setObjectName("showdialog")
        self.fonButton = QtWidgets.QPushButton(self.centralwidget)
        self.fonButton.setGeometry(QtCore.QRect(264, 360, 81, 23))
        self.fonButton.setObjectName("fonButton")
        self.FontTest = QtWidgets.QLineEdit(self.centralwidget)
        self.FontTest.setGeometry(QtCore.QRect(162, 390, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.FontTest.setFont(font)
        self.FontTest.setAutoFillBackground(False)
        self.FontTest.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.FontTest.setFrame(False)
        self.FontTest.setAlignment(QtCore.Qt.AlignCenter)
        self.FontTest.setObjectName("FontTest")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 210, 331, 85))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(True)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setAutoRepeat(False)
        self.checkBox_2.setAutoExclusive(False)
        self.checkBox_2.setTristate(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_3.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setMaximum(999)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 1, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setSingleStep(0.001)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 2, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setTristate(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_3.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.getItem = QtWidgets.QPushButton(self.widget)
        self.getItem.setObjectName("getItem")
        self.gridLayout_4.addWidget(self.getItem, 0, 0, 1, 1)
        self.lineEdit_getItem = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_getItem.setObjectName("lineEdit_getItem")
        self.gridLayout_4.addWidget(self.lineEdit_getItem, 0, 1, 1, 1)
        self.getText = QtWidgets.QPushButton(self.widget)
        self.getText.setObjectName("getText")
        self.gridLayout_4.addWidget(self.getText, 1, 0, 1, 1)
        self.lineEdit_getText = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_getText.setObjectName("lineEdit_getText")
        self.gridLayout_4.addWidget(self.lineEdit_getText, 1, 1, 1, 1)
        self.getInt = QtWidgets.QPushButton(self.widget)
        self.getInt.setObjectName("getInt")
        self.gridLayout_4.addWidget(self.getInt, 2, 0, 1, 1)
        self.lineEdit_getInt = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_getInt.setObjectName("lineEdit_getInt")
        self.gridLayout_4.addWidget(self.lineEdit_getInt, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(383, 21, 648, 360))
        self.widget1.setObjectName("widget1")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.loadImage = QtWidgets.QPushButton(self.widget1)
        self.loadImage.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.loadImage.setFont(font)
        self.loadImage.setObjectName("loadImage")
        self.gridLayout_6.addWidget(self.loadImage, 0, 0, 1, 1)
        self.loadText = QtWidgets.QPushButton(self.widget1)
        self.loadText.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.loadText.setFont(font)
        self.loadText.setObjectName("loadText")
        self.gridLayout_6.addWidget(self.loadText, 0, 1, 1, 1)
        self.Imageshow = QtWidgets.QLabel(self.widget1)
        self.Imageshow.setMinimumSize(QtCore.QSize(320, 320))
        self.Imageshow.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Imageshow.setText("")
        self.Imageshow.setObjectName("Imageshow")
        self.gridLayout_6.addWidget(self.Imageshow, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.widget1)
        self.textEdit.setMinimumSize(QtCore.QSize(320, 320))
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_6.addWidget(self.textEdit, 1, 1, 1, 1)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1060, 23))
        self.menubar.setObjectName("menubar")
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "高瞻宇", "nidayedechegnqing"))
        self.QMessageBox.setText(_translate("QMainWindow", "13_QMessageBox"))
        self.lineEdit_5.setText(_translate("QMainWindow", "Normal"))
        self.lineEdit_6.setText(_translate("QMainWindow", "NoEcho"))
        self.lineEdit_7.setText(_translate("QMainWindow", "Password"))
        self.lineEdit_8.setText(_translate("QMainWindow", "PasswordEchoOnEdit"))
        self.PasswordEchoOnEdit_3.setText(_translate("QMainWindow", "ReadOnly"))
        self.PasswordEchoOnEdit_2.setText(_translate("QMainWindow", "movie tonight"))
        self.Yes.setText(_translate("QMainWindow", "Yes"))
        self.No.setText(_translate("QMainWindow", "No"))
        self.showdialog.setText(_translate("QMainWindow", "showdialog"))
        self.fonButton.setText(_translate("QMainWindow", "Choose Font"))
        self.FontTest.setText(_translate("QMainWindow", "Hello Font Test 干"))
        self.checkBox.setText(_translate("QMainWindow", "无"))
        self.comboBox.setItemText(0, _translate("QMainWindow", "C"))
        self.comboBox.setItemText(1, _translate("QMainWindow", "C++"))
        self.comboBox.setItemText(2, _translate("QMainWindow", "Python"))
        self.comboBox.setItemText(3, _translate("QMainWindow", "Java"))
        self.comboBox.setItemText(4, _translate("QMainWindow", "C#"))
        self.checkBox_2.setText(_translate("QMainWindow", "间"))
        self.checkBox_3.setText(_translate("QMainWindow", "道"))
        self.getItem.setText(_translate("QMainWindow", "getItem"))
        self.getText.setText(_translate("QMainWindow", "getText"))
        self.getInt.setText(_translate("QMainWindow", "getInt"))
        self.loadImage.setText(_translate("QMainWindow", "loadimage"))
        self.loadText.setText(_translate("QMainWindow", "loadtext"))
